### ISSUE TITLE
Mylar3 (0.7.4) not working after fresh install

### ISSUE THREAD

**Issue by Tsuna77** [mylar3/mylar3#1402]
**Describe the bug**
Error when trying to add comic by ID

**CarePackage**
[carepackage_v0.7.4.zip](https://github.com/mylar3/mylar3/files/12386665/carepackage_v0.7.4.zip)

**Environment (please complete the following information):**
 - OS: [e.g. Windows10] Docker on linux (OpenmediaVault : latest)
 - Branch / commit: [e.g. Dev/38aksi1] master

**Additional information**
I just install mylar3 from scratch with docker from linux server. I set CV ID, discord notification, Download torrents client, jackett as Torznab.

No errors on that configuration, When I try to add my first comics... stack on log and nothing on screen proper ...

I try multiple time, with 0.7.4 and 0.7.3 but nothings works :( I don't know what to do now

**Docker compose**
```
---
version: "2.1"
services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest

    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Paris
      - LC_ALL=fr_FR.UTF-8
    volumes:
      - /config/mylar3:/config
      - /partage:/partage
    ports:
      - 8090:8090
    restart: unless-stopped
```
